// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: libs/common/src/proto/orders.proto

/* eslint-disable */

export const protobufPackage = '';

export const _PACKAGE_NAME = '';
